In [1]:
import pandas as pd

In [2]:
table = pd.read_csv("~/Documents/uniAssignments/year_3_sem_1/data_science_week_1/dsc3103-project/data/raw/dirty_cafe_sales.csv")

In [3]:
table.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [4]:
table.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [5]:
table.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [6]:
table.dtypes

Transaction ID      str
Item                str
Quantity            str
Price Per Unit      str
Total Spent         str
Payment Method      str
Location            str
Transaction Date    str
dtype: object